### ISSUE TITLE
Error on running fairing ames model example 

### ISSUE THREAD

**Issue by chaitanyak52** [kubeflow/fairing#273]
/kind bug

I am trying to run  the ames model  prediction  using fairing as per the readme at 
https://github.com/kubeflow/fairing/tree/master/examples/prediction on cloud and  i see pod the following error

 seldon_core.microservice:main:261 - INFO:  Starting microservice.py:main

2019-06-06 11:12:53,898 - seldon_core.microservice:main:292 - INFO:  Annotations: {}

Traceback (most recent call last):

  File "/usr/local/bin/seldon-core-microservice", line 11, in <module>

    sys.exit(main())

  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 294, in main

    interface_file = importlib.import_module(args.interface_name)

  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 994, in _gcd_import

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'HousingServe'
**Environment:**

- Fairing version: (use `python -c "import fairing; print(fairing.__version__)"`):0.5.3

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Can you please let me know where was this example run. Is it run on minikube or gcp and can this be run on any cloud provider.

**Comment by vjrantal** [comment]
I am able to reproduce the same issue. Could it be the same root cause as in the issue discussed at https://github.com/kubeflow/fairing/issues/196#issuecomment-481526203?

**Comment by vjrantal** [comment]
@chaitanyak52 It looks like this kind of change makes the example work https://github.com/vjrantal/fairing/commit/7f58f994d628392d43f01476bd146237cc36c404.

However, I am not sure if the intent is that user would not have to provide the input files like this so not necessarily saying this is the right kind of approach.
