### ISSUE TITLE
Deployer Pod in Crashloopbackoff

### ISSUE THREAD

**Issue by dpaks** [kubeflow/fairing#284]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Ran the foll. commands to setup prediction EP
`fairing.config.set_deployer('serving', serving_class="HousingServe")
create_endpoint = fairing.config.fn(HousingServe)
create_endpoint()`
_Waiting for prediction endpoint to come up..._ is what was shown in the ipython terminal

Pod status was 
fairing-deployer-mcs6v-6ccc5f8698-b5dz2                            0/1     CrashLoopBackOff

**What did you expect to happen:**
Deployment to work, prediction EP to be created

Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
I'm trying it on baremetal, not GCP. Image has been built.

Environment:

Fairing version: (use python -c "import fairing; print(fairing.__version__)"): 0.5.3
Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.5
Minikube version: NIL
Kubernetes version: (use kubectl version): 1.12.5
OS (e.g. from /etc/os-release): Ubuntu 18.04

**Deployer pod logs**
kubectl logs -n xxx fairing-deployer-mcs6v-6ccc5f8698-b5dz2
Traceback (most recent call last):
  File "/usr/local/bin/seldon-core-microservice", line 6, in <module>
    from seldon_core.microservice import main
  File "/usr/local/lib/python3.5/site-packages/seldon_core/microservice.py", line 242
    server.add_insecure_port(f"0.0.0.0:{port}")
                                             ^
SyntaxError: invalid syntax

**Comment by Edwardsleo** [comment]
Myself facing the same issue ....help needed
