### ISSUE TITLE
Traceback when deploy tfjobs

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#296]
/kind bug

**What steps did you take and what happened:**
Traceback when deploy tfjobs, see below.

```
Traceback (most recent call last):
  File "main.py", line 236, in <module>
    fairing.config.run()
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/fairing/config.py", line 106, in run

�
    deployer.deploy(pod_spec)
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/fairing/deployers/job/job.py", line 66, in deploy
    name = self.create_resource()
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/fairing/deployers/tfjob/tfjob.py", line 23, in create_resource
    self.created_tfjob = self.backend.create_tf_job(self.namespace, self.deployment_spec)
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/fairing/kubernetes/manager.py", line 36, in create_tf_job
    job
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/kubernetes/client/apis/custom_objects_api.py", line 178, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/kubernetes/client/apis/custom_objects_api.py", line 277, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Fairing version: (use `python -c "import fairing; print(fairing.__version__)"`): 0.5.3
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.5
- Minikube version: 
- Kubernetes version: (use `kubectl version`): 1.11
- OS (e.g. from `/etc/os-release`): redhat

**NOTE**: If you are using fair from master, please provide us the git commit hash.

**Comment by jinchihe** [comment]
Checked more, seems that's caused by tfjobs version is out of date. From the Kubeflow, the tfjobs version is updated to `v1beta2` at least, but in the Fairing, tfjobs version still be `v1beta1`. We need to upgrade that. 

Will send a PR to upgrade this. Thanks.
