### ISSUE TITLE
Connection broken while following logs after deploying few minutes.

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#437]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

Connection broken while following logs after deploying few minutes.

```
[W 191230 22:45:17 job:90] The job fairing-job-l7s6p launched.
[W 191230 22:45:18 manager:263] Waiting for fairing-job-l7s6p-ppt4s to start...
[W 191230 22:45:18 manager:263] Waiting for fairing-job-l7s6p-ppt4s to start...
[W 191230 22:45:18 manager:263] Waiting for fairing-job-l7s6p-ppt4s to start...
[W 191230 22:45:26 manager:263] Waiting for fairing-job-l7s6p-ppt4s to start...
[I 191230 22:45:32 manager:269] Pod started running True
2019-12-31 06:45:38.710579: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-31 06:45:38.722321: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199960000 Hz
2019-12-31 06:45:38.723238: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4ada4b0 executing computations on platform Host. Devices:
2019-12-31 06:45:38.723291: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/opt/python3/python36/lib/python3.6/site-packages/urllib3/response.py", line 685, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3/python36/lib/python3.6/site-packages/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/opt/python3/python36/lib/python3.6/site-packages/urllib3/response.py", line 752, in read_chunked
    self._update_chunk_length()
  File "/opt/python3/python36/lib/python3.6/site-packages/urllib3/response.py", line 689, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 81, in <module>
    fairing.config.run()
  File "/opt/python3/python36/lib/python3.6/site-packages/kubeflow/fairing/config.py", line 133, in run
    deployer.deploy(pod_spec)
  File "/opt/python3/python36/lib/python3.6/site-packages/kubeflow/fairing/deployers/job/job.py", line 93, in deploy
    self.get_logs()
  File "/opt/python3/python36/lib/python3.6/site-packages/kubeflow/fairing/deployers/job/job.py", line 155, in get_logs
    container="fairing-job")
  File "/opt/python3/python36/lib/python3.6/site-packages/kubeflow/fairing/kubernetes/manager.py", line 297, in log
    for chunk in tail.stream(MAX_STREAM_BYTES):
  File "/opt/python3/python36/lib/python3.6/site-packages/urllib3/response.py", line 560, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/python3/python36/lib/python3.6/site-packages/urllib3/response.py", line 781, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/python3/python36/lib/python3.6/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
(python36) [root@jche-inf kubeflow]# date
Mon Dec 30 22:47:29 PST 2019
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Fairing version: (use `python -c "import kubeflow.fairing; print(kubeflow.fairing.__version__)"`):
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**NOTE**: If you are using fair from master, please provide us the git commit hash.

**Comment by jinchihe** [comment]
Seems that's caused by the connection breaken of kubernetes API, that's better to retry if the connect timeout.

/assign
