### ISSUE TITLE
pip install kubeflow-fairing is failing due to requirements.txt is not found

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/fairing#451]
pip install kubeflow-fairing fails due to requirements.txt is not found

```
# pip install kubeflow-fairing-0.7.1.tar.gz
Processing ./kubeflow-fairing-0.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-knClDK-build/setup.py", line 3, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

```

**Comment by jinchihe** [comment]
Why
```
pip install kubeflow-fairing-0.7.1.tar.gz ?
```
I think should be 
```
pip install kubeflow-fairing
```

**Comment by hemantha-kumara** [comment]
Maybe an issue with python version I am using.
In python3, I don't see the error. it was my mistake.
