### ISSUE TITLE
Cannot run MNIST example because packages cannot be installed

### ISSUE THREAD

**Issue by allenc97** [kubeflow/fairing#489]
It appears that azure 5.0.0 is causing notebook_setup.py to break.
```
tf-docker ~/git_kubeflow-examples/mnist > pip3 install --user -r requirements.txt
Collecting git+git://github.com/kubeflow/fairing.git@7e4c23c47a6b0544a722d04e1f9910c2f283a4f6 (from -r requirements.txt (line 2))
  Cloning git://github.com/kubeflow/fairing.git (to revision 7e4c23c47a6b0544a722d04e1f9910c2f283a4f6) to /tmp/pip-req-build-iq9d2dl6
  Running command git clone -q git://github.com/kubeflow/fairing.git /tmp/pip-req-build-iq9d2dl6
  Running command git checkout -q 7e4c23c47a6b0544a722d04e1f9910c2f283a4f6
Collecting retrying==1.3.3
  Using cached retrying-1.3.3.tar.gz (10 kB)
Requirement already satisfied: google-api-core[grpc]>=1.15.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4)) (1.16.0)
Collecting python-dateutil<=2.8.0,>=2.1
  Using cached python_dateutil-2.8.0-py2.py3-none-any.whl (226 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (1.18.1)
Collecting kfserving>=0.2.1.1
  Using cached kfserving-0.3.0.1-py3-none-any.whl (83 kB)
Requirement already satisfied: docker>=3.4.1 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (4.1.0)
Requirement already satisfied: notebook>=5.6.0 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-rrequirements.txt (line 2)) (6.0.3)
Requirement already satisfied: kubernetes>=10.0.1 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (10.0.1)
Requirement already satisfied: future>=0.17.1 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (0.18.2)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python3/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: google-cloud-storage>=1.13.2 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (1.25.0)
Collecting google-cloud-logging>=1.13.0
  Using cached google_cloud_logging-1.15.0-py2.py3-none-any.whl (141 kB)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (2.22.0)
Requirement already satisfied: setuptools>=34.0.0 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (45.1.0)
Requirement already satisfied: google-auth>=1.6.2 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: httplib2>=0.12.0 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (0.17.0)
Requirement already satisfied: oauth2client>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (4.1.3)
Collecting tornado>=6.0.1
  Using cached tornado-6.0.4.tar.gz (496 kB)
Requirement already satisfied: google-api-python-client>=1.7.8 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (1.7.11)
Requirement already satisfied: cloudpickle>=0.8 in /usr/local/lib/python3.6/dist-packages (from kubeflow-fairing==0.7.1->-r requirements.txt (line 2)) (1.2.2)
Collecting urllib3==1.24.2
  Using cached urllib3-1.24.2-py2.py3-none-any.whl (131 kB)
Collecting boto3>=1.9.0
  Using cached boto3-1.12.42-py2.py3-none-any.whl (128 kB)
Collecting azure>=4.0.0
  Using cached azure-5.0.0.zip (4.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7ph3oukm/azure/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7ph3oukm/azure/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-7ph3oukm/azure/pip-egg-info
         cwd: /tmp/pip-install-7ph3oukm/azure/
    Complete output (24 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7ph3oukm/azure/setup.py", line 60, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
    -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
    -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
    -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
    -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts

    A more comprehensive discussion of the rationale for this decision can be found in the following issue:
    https://github.com/Azure/azure-sdk-for-python/issues/10646


    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
tf-docker ~/git_kubeflow-examples/mnist >
```

**Comment by allenc97** [comment]
A quick fix is to run
```
pip3 install --user azure==4.0.0
```
before the subprocess call in notebook_setup. According to https://pypi.org/project/azure/, this package has been deprecated as of 04/08/2020.

**Comment by jinchihe** [comment]
The problem should be already fixed in https://github.com/kubeflow/fairing/pull/482

Please reopen if you still have the problem, thanks.
